### ISSUE TITLE
Ven's variants of Folding panels start out extended

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/ROSolar#1]
(from discord; logging so it doesn't get forgotten)

Place a panel, leave it collapsed, and switch variants; all the restock variants stay collapsed, but the ven's variants are extended. However the PAW button still says 'extend solar panel', and clicking it performs the animation and leaves the panel extended. So something's inconsistent in the part's internal state.

Worse, if the panel is manually collapsed, then the craft saved (or queued to kct), the next time the same vessel is opened (in VAB or on the pad), the panels will be extended again. (especially a problem on the pad, since there's no 'collapse' button there

**Comment by DRVeyl** [comment]
Fixed with https://github.com/KSP-RO/ROSolar/releases/tag/v0.2 and https://github.com/KSP-RO/ROLibrary/releases/tag/v0.3
