### ISSUE TITLE
Folding panels stay stuck in 'extending' state

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/ROSolar#2]
(from discord)

A Folding panel that's extended in flight never actually reaches the 'extended' state; it stays stuck in 'extending' even after the animation completes, and never starts producing EC.

Workaround: quicksave, manually change the state to 'extended' in the .sfs, quickload

Appears to affect all variants. Haven't actually tried manually extending a panel; all instances I've noticed were after MJ/PVG auto-extend

**Comment by lpgagnon** [comment]
I _have_ now tried with a manual extend, same behavior.

**Comment by DRVeyl** [comment]
Fixed with https://github.com/KSP-RO/ROSolar/releases/tag/v0.2 and https://github.com/KSP-RO/ROLibrary/releases/tag/v0.3
