### ISSUE TITLE
Ranger(sm) panel overstates its area

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/ROSolar#8]
from discord https://discord.com/channels/319857228905447436/663102368887472156/729339197743169618

ROS-HingedSolarPanel, Trapezoid variant, Ranger(sm) design reports an area that's maybe double what it should be. (Wing design looks more reasonable, have not looked at others)

**Comment by DRVeyl** [comment]
Fixed in <https://github.com/KSP-RO/ROSolar/commit/4bc8846f714be688976286a2537364028fdf3263>
